FROM truesight.asia:8443/aspnet:3.1-buster-slim AS base
WORKDIR /app
RUN apt-get update && apt-get install -y net-tools curl iputils-ping telnet nano vim libc6-dev libgdiplus

FROM truesight.asia:8443/dotnet-sdk:3.1-buster AS build
WORKDIR /src
COPY ["{{Namespace}}.csproj", "./"]
RUN dotnet restore "{{Namespace}}.csproj"
COPY . .
WORKDIR "/src"
RUN dotnet build "{{Namespace}}.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "{{Namespace}}.csproj" -c Release -o /app/publish

FROM base AS final

WORKDIR /app

COPY --from=truesight.asia:8443/consul:stable /bin/consul /usr/local/bin/consul
COPY --from=truesight.asia:8443/envoy:stable /usr/local/bin/envoy /usr/local/bin/envoy

COPY /consul /consul/config

COPY --from=publish /app/publish .

COPY ["docker-entrypoint.sh", "."]

RUN chmod a+x docker-entrypoint.sh

CMD ["./docker-entrypoint.sh"]

EXPOSE 80
